	deb <- gsub("\\[<i>applause</i><b>\\] </b>", "", deb)
	deb <- gsub("\\[<i>applause</i>\\]", "", deb)
	deb <- gsub("\\[<i>sic</i>\\]", "", deb)
	deb <- gsub("\\[<i>crosstalk</i>\\]", "", deb)
	deb <- gsub("\\[<i>laughter</i>\\]", "", deb)
	deb <- gsub("\\[<i>laughter and applause</i>\\]", "", deb)
	deb <- gsub("\\[<i>commercial break</i>\\]", "", deb)
	deb <- gsub("\\(COMMERCIAL BREAK\\)", "", deb)
	deb <- gsub("\\(APPLAUSE\\)", "", deb)
	deb <- gsub("\\(inaudible\\)", "", deb)
	deb <- gsub("\\(Laughter\\)", "", deb)
	deb <- gsub("\\(sic\\)", "", deb)
	deb <- gsub("\\n", "", deb)
	deb <- gsub("<br>", "", deb)

	deb <- gsub("<BR>", "", deb)
	deb <- gsub("<BR/>", "", deb)
	deb <- gsub('\"',"", deb)
	deb <- gsub('<strong>',"", deb)
	deb <- gsub('</strong>',"", deb)
	deb <- gsub('<h1>',"", deb)
	deb <- gsub('</h1>',"", deb) 
	deb <- gsub('</p>',"", deb) 
	deb <- gsub('<div id=content-sm>',"", deb) 
	deb <- gsub("\\(chuckle\\)", "", deb)
 	deb <- gsub('\\(barely audible\\)',"", deb) 
 	deb <- gsub('\\(laughter from audience\\)',"", deb) 
	deb <- gsub("\\[Laughter\\]", "", deb)
	deb <- gsub("\\[applause\\]", "", deb)
	deb <- gsub("\\[Laughter and applause\\]", "", deb)
	deb <- gsub("\\[Applause\\]", "", deb)
	deb <- gsub("\\[\\]", "", deb)
	deb <- gsub("\\[laughter\\]", "", deb)
	deb <- gsub("\\(Applause\\)", "", deb)
	deb <- gsub("\\(Shouts and applause\\)", "", deb)
	deb <- gsub("\\(Prolonged shouts and applause\\)", "", deb)
	deb <- gsub("\\(Laughter, boos\\)", "", deb)
	deb <- gsub("\\(Laughter and applause\\)", "", deb)
	deb <- gsub("\\(Cheers and Applause\\)", "", deb)
	deb <- gsub("\\(phonetic\\)", "", deb)
	deb <- gsub("\\(Scattered applause\\)", "", deb)
	deb <- gsub("\\(Shouts, laughter\\)", "", deb)
	deb <- gsub("\\(Equal amounts of cheering and booing\\)", "", deb)
	deb <- gsub("\\(Laughter, scattered applause\\)", "", deb)
	deb <- gsub("\\(Laughter, applause\\)", "", deb)
	deb <- gsub("\\(Scattered laughter\\)", "", deb)
	deb <- gsub("\\(Boos and applause\\)", "", deb)
	deb <- gsub("\\[Laughter.\\]", "", deb)
	deb <- gsub("\\(Laughter.\\)", "", deb)


	deb <- gsub("\\(Audience: No.\\)", "", deb)
	deb <- gsub("\\(Inaudible\\)", "", deb)
	deb <- gsub("\\(Laughs\\)", "", deb)
	deb <- gsub("</span>", "", deb)
	deb <- gsub("\\(APPLAUSE.\\)", "", deb)
	deb <- gsub("\\(Simultaneous conversation\\)", "", deb)

	deb <- gsub("\\(Jeers.\\)", "", deb)
	deb <- gsub("\\(laughter\\)", "", deb)